#!/usr/bin/env python3
"""scripts/remeasure_v015.py — re-measure v015 under its OWN live gates (full-history methodology).

Motivation: the dossier's fresh 2025-26 Sharpe (-0.085) was generated by a SHORT-WINDOW run
(prove.py --start 2025-01-01) where the per-pair VIX regime gates never warm up → ungated v015.
This regenerates ONE full-history gate-active ledger (backtest_all, which reconciles OOS at ~1.17),
extracts the 2025+ slice (gated v015 measured properly), and reports the corrected fresh Sharpe +
the corrected year-by-year trajectory vs the documented (mixed-method) sequence.

READ-ONLY w.r.t. live config; regenerates the trades file then RESTORES the dossier backup. No
HYP-065 work, no regime tagging, no commits.

    python3 scripts/remeasure_v015.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sovereign.reporting.equity_curve import _sharpe, weighted_portfolio_sharpe  # noqa: E402

TRADES_FILE = ROOT / "logs/forex_backtest_trades.json"
DOSSIER_BACKUP = ROOT / "logs/forex_backtest_trades_dossier_20260627.json"
OUT_MD = ROOT / "docs/research/v015_remeasurement.md"
PAIRS = ["EURUSD", "GBPUSD", "USDJPY", "AUDUSD"]
DOCUMENTED = {"2021": -0.13, "2022": 0.51, "2023": 1.26, "2024": -0.09, "2025-26": -0.085}


def _load_trades(path: Path) -> pd.DataFrame:
    raw = json.loads(path.read_text())
    rows = []
    for tk, tl in raw.items():
        p = tk.replace("=X", "")
        for t in tl:
            rows.append({"pair": p,
                         "entry_date": pd.Timestamp(t["entry_date"]).normalize(),
                         "rapnl": float(t.get("risk_adjusted_pnl_pct", t.get("pnl_pct", 0.0)))})
    return pd.DataFrame(rows)


def _pair_sharpe(g: pd.DataFrame) -> float:
    if len(g) < 2:
        return 0.0
    yrs = max((g["entry_date"].max() - g["entry_date"].min()).days / 365.25, 0.25)
    return _sharpe(g["rapnl"].tolist(), yrs)


def _portfolio_sharpe(df: pd.DataFrame) -> float:
    if df.empty:
        return 0.0
    return weighted_portfolio_sharpe([(_pair_sharpe(g), len(g)) for _p, g in df.groupby("pair")])


def _year_mask(df, y):
    if y == "2025-26":
        return df.entry_date >= pd.Timestamp("2025-01-01")
    return (df.entry_date >= pd.Timestamp(f"{y}-01-01")) & (df.entry_date <= pd.Timestamp(f"{y}-12-31"))


def main() -> dict:
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    # 1) full-history gate-active ledger
    from sovereign.forex.forex_backtester import ForexBacktester
    ForexBacktester(start="2015-01-01", end="2026-06-30").backtest_all()   # writes TRADES_FILE (gated)
    gated = _load_trades(TRADES_FILE)
    ungated = _load_trades(DOSSIER_BACKUP) if DOSSIER_BACKUP.exists() else pd.DataFrame(columns=gated.columns)

    fresh_g = gated[gated.entry_date >= pd.Timestamp("2025-01-01")]
    fresh_u = ungated  # the dossier backup IS the 2025-26 ungated slice

    per_pair = {}
    for p in PAIRS:
        g = fresh_g[fresh_g.pair == p]; u = fresh_u[fresh_u.pair == p]
        per_pair[p] = {"gated_n": len(g), "gated_sharpe": round(_pair_sharpe(g), 3),
                       "ungated_n": len(u), "ungated_sharpe": round(_pair_sharpe(u), 3)}

    traj = {y: {"gated": round(_portfolio_sharpe(gated[_year_mask(gated, y)]), 3),
                "documented": DOCUMENTED[y]} for y in DOCUMENTED}

    out = {
        "fresh_gated_portfolio_sharpe": round(_portfolio_sharpe(fresh_g), 3),
        "fresh_ungated_portfolio_sharpe_dossier": round(_portfolio_sharpe(fresh_u), 3),
        "dossier_documented_fresh": -0.085,
        "oos_2023_24_gated": round(_portfolio_sharpe(gated[_year_mask(gated, "2023") | _year_mask(gated, "2024")]), 3),
        "per_pair_fresh": per_pair,
        "trajectory": traj,
        "eurusd_gated_fresh_sharpe": per_pair["EURUSD"]["gated_sharpe"],
    }
    _write_md(out)
    # restore the dossier artifact (preserve evidence chain)
    if DOSSIER_BACKUP.exists():
        TRADES_FILE.write_text(DOSSIER_BACKUP.read_text())
    return out


def _write_md(o: dict) -> None:
    pp = o["per_pair_fresh"]
    L = ["# v015 Re-measurement — fresh period under LIVE gates (full-history methodology)", "",
         "> The dossier's fresh -0.085 came from a short-window run where the VIX gates never warmed "
         "up (ungated v015). This re-measures fresh 2025-26 from the full-history gate-active ledger "
         "(which reconciles OOS 2023-24). Sharpe = √n-weighted costed portfolio (risk_adjusted_pnl_pct).", "",
         "## Headline", "",
         f"- **Gated v015 fresh 2025-26 portfolio Sharpe: {o['fresh_gated_portfolio_sharpe']}**",
         f"- Ungated (dossier backup) fresh portfolio Sharpe: {o['fresh_ungated_portfolio_sharpe_dossier']} "
         f"(documented headline -0.085)",
         f"- Sanity: full-history OOS 2023-24 gated Sharpe {o['oos_2023_24_gated']} (≈ documented 1.25)", "",
         "## Fresh 2025-26 by pair — gated vs ungated", "",
         "| pair | gated n | gated Sharpe | ungated n | ungated Sharpe |", "|---|---|---|---|---|"]
    for p in PAIRS:
        v = pp[p]
        L.append(f"| {p} | {v['gated_n']} | {v['gated_sharpe']} | {v['ungated_n']} | {v['ungated_sharpe']} |")
    L += ["", f"**EURUSD (load-bearing — its VIX>18 gate didn't fire this window, so gated≈ungated): "
          f"fresh Sharpe {o['eurusd_gated_fresh_sharpe']}.** If EURUSD is still negative under proper "
          "gating, the collapse is real regardless of USDJPY's gate effect.", "",
          "## Corrected trajectory (gated, one consistent method) vs documented (mixed methods)", "",
          "| Year | Documented | Gated-corrected |", "|---|---|---|"]
    for y, v in o["trajectory"].items():
        L.append(f"| {y} | {v['documented']:+} | {v['gated']:+} |")
    L += ["", "## Read", "",
          ("The dossier's -0.085 vs the gated fresh Sharpe above shows how much the missing live gates "
           "moved the number. If gated fresh is still ~0 or negative (esp. EURUSD), the collapse is REAL "
           "and HYP-065 (regime conditionality) remains a live question on a clean ledger. If gated fresh "
           "recovers to clearly positive, the 'collapse' was largely a short-window gating artifact and "
           "the question changes."), ""]
    OUT_MD.write_text("\n".join(L) + "\n")


if __name__ == "__main__":
    o = main()
    print("=" * 76)
    print("v015 RE-MEASUREMENT (fresh under live gates, full-history method)")
    print(f"  GATED fresh 2025-26 portfolio Sharpe : {o['fresh_gated_portfolio_sharpe']}")
    print(f"  UNGATED (dossier) fresh portfolio    : {o['fresh_ungated_portfolio_sharpe_dossier']}  (documented -0.085)")
    print(f"  OOS 2023-24 gated (sanity ≈1.25)     : {o['oos_2023_24_gated']}")
    print("  fresh by pair (gated n/Sharpe | ungated n/Sharpe):")
    for p in PAIRS:
        v = o["per_pair_fresh"][p]
        print(f"    {p}: gated {v['gated_n']}/{v['gated_sharpe']:+}   ungated {v['ungated_n']}/{v['ungated_sharpe']:+}")
    print(f"  EURUSD gated fresh Sharpe (load-bearing): {o['eurusd_gated_fresh_sharpe']:+}")
    print("  corrected trajectory (documented -> gated):")
    for y, v in o["trajectory"].items():
        print(f"    {y}: {v['documented']:+} -> {v['gated']:+}")
    print("  (dossier trades file restored)")
    print("=" * 76)
